# -*- coding: utf-8 -*-
"""
Created on Mon Aug 27 08:15:12 2018

@author: thomapb4
"""

# -*- coding: utf-8 -*-
"""
Created on Tue Jul 17 18:04:16 2018

@author: Tom
"""

import pandas as pd


### crosswalks ###
#roster_comb = pd.read_csv("U:/Data/Desktop Backup/Book3.csv", encoding='ISO-8859-1')

univ_Dict = {"Adrian":"Adrian College",
"Albion College Athletics":"Albion College",
"Alfred State College Athletics":"Alfred State",
"Alma College Athletics":"Alma College",
"Amherst College":"Amherst College",
"Anna Maria":"Anna Maria College",
"Apprentice School":"The Apprentice School",
"Athletic & Academic Excellence Cal Poly":"Cal Poly",
"Austin College":"Austin College",
"Baldwin Wallace Athletics":"Baldwin Wallace",
"Bates College":"Bates College",
"Becker":"Becker College",
"Bentley University Falcons":"Bentley",
"Bethany":"Bethany College",
"Bowdoin":"Bowdoin College",
"Brevard College":"Brevard College",
"Bridgewater Eagles":"Bridgewater College",
"Bridgewater St.":"Bridgewater State",
"Bryant University Bulldogs":"Bryant",
"Buffalo":"Buffalo",
"California Lutheran University":"California Lutheran",
"Capital University Athletics":"Capital",
"Carnegie Mellon University Athletics":"Carnegie Mellon",
"Case Western Reserve":"Case Western",
"Castleton":"Castleton",
"CCSU":"Central Connecticut State",
"Chapman":"Chapman",
"Claremont Mudd Scripps":"Claremont-Mudd-Scripps",
"Coast Guard":"U.S. Coast Guard Academy",
"Colby College Athletics":"Colby College",
"Concordia (MN)":"Concordia St. Paul",
"Concordia University Wisconsin":"Concordia Wisconsin",
"Dakota Wesleyan University":"Dakota Wesleyan",
"Dean College":"Dean College",
"Denison University Big Red":"Denison",
"DePauw Athletics":"Depauw",
"Earlham College Athletics":"Earlham College",
"Emory & Henry":"Emory & Henry College",
"Endicott Athletics and Recreation":"Endicott College",
"Eureka College":"Eureka College",
"Evangel University":"Evangel",
"Ferris State Bulldogs":"Ferris State",
"FIGHTIN'ENGINEERS":"Rose-Hulman Institute Of Technology",
"Findlay":"Findlay",
"Fitchburg State":"Fitchburg State",
"Framingham St.":"Framingham State",
"Franklin College":"Franklin College",
"Furman University Athletics":"Furman",
"George Fox Athletics":"George Fox",
"GoTiffinDragons.com : Tiffin University Official Athletic Site":"Tiffin",
"Hamilton Athletics":"Hamilton College",
"Heidelberg University":"Heidelberg",
"Hillsdale College Athletics":"Hillsdale College",
"Hiram College":"Hiram College",
"Home of Berry College Athletics Berry Vikings":"Berry College",
"Hope College Athletics":"Hope",
"Huntingdon":"Huntingdon College",
"Jacksonville University":"Jacksonville",
"Juniata":"Juniata College",
"Kalamazoo College":"Kalamazoo College",
"Lake Forest College Athletics ":"Lake Forest College",
"Lawrence Athletics":"Lawrence",
"Lewis & Clark":"Lewis & Clark College",
"Maine Maritime":"Maine Maritime Academy",
"MANCHESTER UNIVERSITY SPARTAN ATHLETICS":"Manchester",
"Mars Hill University":"Mars Hill",
"McDaniel College":"Mcdaniel College",
"Michigan Tech Athletics":"Michigan Tech",
"Moravian College":"Moravian College",
"Morrisville State Athletics":"Morrisville State College",
"MSJ SPORTSMount St. Joseph University Athletics":"Mount St. Joseph",
"Muskingum University Athletics":"Muskingum",
"Northern Michigan University":"Northern Michigan",
"Northwood University Athletics (Michigan)":"Northwood Michigan",
"NorwichAthletics":"Norwich",
"Occidental":"Occidental College",
"Official Athletics Site of Defiance College":"Defiance College",
"Official Site Of Catholic Athletics":"Catholic America",
"Official Website of Maryville College Athletics":"Maryville College",
"Ohio Dominican":"Ohio Dominican",
"Ohio Northern":"Ohio Northern",
"Ohio University":"Ohio",
"Olivet":"Olivet College",
"Plymouth State":"Plymouth State",
"Pomona Pitzer":"Pomona Pitzer",
"Randolph-Macon":"Randolph-Macon",
"Redlands":"Redlands",
"Rockford University Athletics":"Rockford",
"Sacramento State Athletics":"Sacramento State",
"Saginaw Valley State":"Saginaw Valley",
"Salve Regina":"Salve Regina",
"Sewanee Athletics":"Sewanee",
"Shaw":"Shaw",
"Shenandoah":"Shenandoah",
"Siena Heights":"Siena Heights",
"Southwestern Community College":"Southwestern",
"Springfield College Athletics":"Springfield College",
"Stonehill College Skyhawks":"Stonehill College",
"Tennessee Tech":"Tennessee Tech",
"THE OFFICIAL HOME OF MASSACHUSETTS MARITIME ATHLETICS":"Mass Maritime",
"The Official Website Of Blugold Athletics":"Wisconsin Eau Claire",
"The Official Website of Curry College Athletics":"Curry College",
"THE OFFICIAL WEBSITE OF HUSSON UNIVERSITY ATHLETICS":"Husson",
"The Official Website of North Carolina Wesleyan College Athletics":"North Carolina Wesleyan College",
"The Official Website Of the Birmingham-Southern Panthers":"Birmingham Southern College",
"The official Website of the Greenville College Panthers":"Greenville",
"The University of Chicago Athletics":"Chicago",
"Thomas More Athletics":"Thomas More College",
"Trine University ":"Trine",
"Trinity (TX)":"Trinity",
"Trinity Bible College":"Trinity Bible College",
"Tufts":"Tufts",
"Tusculum Pioneers":"Tusculum College",
"UMass Dartmouth":"UMass Dartmouth",
"University of Mount Union Athletics":"Mount Union",
"University of St. Thomas":"St. Thomas",
"University of Wisconsin-Oshkosh Athletics":"Wisconsin Oshkosh",
"Ursinus College Athletics":"Ursinus College",
"USMMA":"Merchant Marine",
"Wesley":"Wesley College",
"Wesleyan Athletics":"Wesleyan",
"Western Connecticut State University":"Western Connecticut State",
"Western New England University":"Western New England",
"Where Champions Are Made.":"La Verne",
"Whittier College":"Whittier College",
"Whitworth":"Whitworth",
"Willamette University":"Willamette",
"Williams":"Williams College",
"Wilmington College":"Wilmington College",
"Wisconsin Lutheran College Athletics":"Wisconsin Lutheran College",
"Wittenberg TigersOfficial Site of Wittenberg University Athletics":"Wittenberg",
"Worcester State":"Worcester State",
"WUSTL Athletics":"Washington St. Louis",
"Youngstown State":"Youngstown State",
"Washington & Lee":"Washington & Lee"}


pos_Dict = {" ":"Unknown",
"0":"Unknown",
"40":"Unknown",
"-":"Unknown",
"A":"RB - Running Back",
"A-Back":"RB - Running Back",
"AC":"RB - Running Back",
"AT":"Ath - Athlete",
"ATH":"Ath - Athlete",
"Ath.":"Ath - Athlete",
"ATHL":"Ath - Athlete",
"Athlete":"Ath - Athlete",
"ATH-O":"Ath - Athlete",
"B":"RB - Running Back",
"BAN":"RB - Running Back",
"Bandit":"RB - Running Back",
"B-B":"RB - Running Back",
"B-Back":"RB - Running Back",
"Bear":"RB - Running Back",
"BS":"RB - Running Back",
"Buck":"RB - Running Back",
"C":"C - Center",
"C/DE":"C - Center",
"C/G":"C - Center",
"C/LG":"C - Center",
"C/LS":"C - Center",
"C/OG":"C - Center",
"C/OL":"C - Center",
"C/OT":"C - Center",
"CB":"CB - Cornerback",
"CB (C)":"CB - Cornerback",
"CB/ATH":"CB - Cornerback",
"CB/HLD":"CB - Cornerback",
"CB/K":"CB - Cornerback",
"CB/KR":"CB - Cornerback",
"CB/LS":"CB - Cornerback",
"CB/RB":"CB - Cornerback",
"CB/S":"CB - Cornerback",
"CB/SS":"CB - Cornerback",
"CB/WR":"CB - Cornerback",
"Center":"C - Center",
"Cornerback":"CB - Cornerback",
"D":"DB - Defensive Back",
"D/M":"DB - Defensive Back",
"D/RB":"DB - Defensive Back",
"DB":"DB - Defensive Back",
"DB / K":"DB - Defensive Back",
"DB / KOS":"DB - Defensive Back",
"DB / P":"DB - Defensive Back",
"DB ":"DB - Defensive Back",
"DB/K":"DB - Defensive Back",
"DB/K/P":"DB - Defensive Back",
"DB/KR":"DB - Defensive Back",
"DB/LB":"DB - Defensive Back",
"DB/LS":"DB - Defensive Back",
"DB/OLB":"DB - Defensive Back",
"DB/P":"DB - Defensive Back",
"DB/P/K":"DB - Defensive Back",
"DB/PK":"DB - Defensive Back",
"DB/QB":"DB - Defensive Back",
"DB/RB":"DB - Defensive Back",
"DB/SS":"DB - Defensive Back",
"DB/WR":"DB - Defensive Back",
"DB/WR/RB":"DB - Defensive Back",
"DB`":"DB - Defensive Back",
"DBÃ¯Â¿Â½":"DB - Defensive Back",
"DBC":"DB - Defensive Back",
"DBS":"DB - Defensive Back",
"DB-WR":"DB - Defensive Back",
"DE":"DE - Defensive End",
"DE ":"DE - Defensive End",
"DE/ LB":"DE - Defensive End",
"DE/DT":"DE - Defensive End",
"DE/LB":"DE - Defensive End",
"DE/LS":"DE - Defensive End",
"DE/NG":"DE - Defensive End",
"DE/OL":"DE - Defensive End",
"DE/OL/TE":"DE - Defensive End",
"DE/OLB":"DE - Defensive End",
"DE/P":"DE - Defensive End",
"DE/RB":"DE - Defensive End",
"DE/TE":"DE - Defensive End",
"DEÃ¯Â¿Â½":"DE - Defensive End",
"Defensive Back":"DB - Defensive Back",
"Defensive Back / Wide Receiver":"DB - Defensive Back",
"Defensive Back, Punter":"DB - Defensive Back",
"Defensive End":"DE - Defensive End",
"Defensive End/TE":"DE - Defensive End",
"Defensive Line":"DL - Defensive Lineman",
"Defensive Line/Offensive Line":"DL - Defensive Lineman",
"Defensive Lineman":"DL - Defensive Lineman",
"Defensive Tackle":"DT - Defensive Tackle",
"DI":"DL - Defensive Lineman",
"DL":"DL - Defensive Lineman",
"DL / LS":"DL - Defensive Lineman",
"DL / P":"DL - Defensive Lineman",
"DL ":"DL - Defensive Lineman",
"DL/FB":"DL - Defensive Lineman",
"DL/K":"DL - Defensive Lineman",
"DL/LB":"DL - Defensive Lineman",
"DL/LS":"DL - Defensive Lineman",
"DL/OL":"DL - Defensive Lineman",
"DL/P":"DL - Defensive Lineman",
"DL/Sn":"DL - Defensive Lineman",
"DL/TE":"DL - Defensive Lineman",
"DL`":"DL - Defensive Lineman",
"DLÃ¯Â¿Â½":"DL - Defensive Lineman",
"Dog":"Ath - Athlete",
"DS":"Ath - Athlete",
"DS/FB":"Ath - Athlete",
"DS/TE":"Ath - Athlete",
"DSn":"Ath - Athlete",
"DT":"DT - Defensive Tackle",
"DT / DE":"DT - Defensive Tackle",
"DT / LS":"DT - Defensive Tackle",
"DT/ NG":"DT - Defensive Tackle",
"DT/DE":"DT - Defensive Tackle",
"DT/G":"DT - Defensive Tackle",
"DT/OL":"DT - Defensive Tackle",
"DT/P":"DT - Defensive Tackle",
"DT/TE":"DT - Defensive Tackle",
"F":"FB - Fullback",
"FB":"FB - Fullback",
"FB ":"FB - Fullback",
"FB/DE":"FB - Fullback",
"FB/H":"FB - Fullback",
"FB/HB":"FB - Fullback",
"FB/ILB":"FB - Fullback",
"FB/K":"FB - Fullback",
"FB/LB":"FB - Fullback",
"FB/LS":"FB - Fullback",
"FB/MLB":"FB - Fullback",
"FB/P":"FB - Fullback",
"FB/RB":"FB - Fullback",
"FB/SN":"FB - Fullback",
"FB/TE":"FB - Fullback",
"FBÃ¯Â¿Â½":"FB - Fullback",
"FL":"WR - Wide Receiver",
"Flex":"WR - Wide Receiver",
"Fr.":"Unknown",
"Free Safety":"FS - Free Safety",
"FS":"FS - Free Safety",
"FS/DB":"FS - Free Safety",
"FS/K":"FS - Free Safety",
"FS/P":"FS - Free Safety",
"FS/PR/LS":"FS - Free Safety",
"FS/SS":"FS - Free Safety",
"Fullback":"FB - Fullback",
"G":"OG - Offensive Guard",
"G/C":"OG - Offensive Guard",
"G/DT":"OG - Offensive Guard",
"G/T":"OG - Offensive Guard",
"G-C":"OG - Offensive Guard",
"GK":"Unknown",
"Gr.":"Unknown",
"H":"RB - Running Back",
"H Back":"RB - Running Back",
"H/QB":"RB - Running Back",
"Halfback":"RB - Running Back",
"HB":"RB - Running Back",
"H-B":"RB - Running Back",
"HB/DL":"RB - Running Back",
"HB/FB ":"RB - Running Back",
"HB/FBÃ¯Â¿Â½":"RB - Running Back",
"H-back":"RB - Running Back",
"HM":"RB - Running Back",
"HR":"RB - Running Back",
"ILB":"MLB - Middle Linebacker",
"ILB/LS":"MLB - Middle Linebacker",
"IR":"Unknown",
"J":"Unknown",
"J-Back":"RB - Running Back",
"JR":"Unknown",
"K":"PK - Placekicker",
"K / DB":"PK - Placekicker",
"K, P":"PK - Placekicker",
"K/DB":"PK - Placekicker",
"K/DL":"PK - Placekicker",
"K/FS":"PK - Placekicker",
"K/LB":"PK - Placekicker",
"K/P":"PK - Placekicker",
"K/P ":"PK - Placekicker",
"K/P/DB":"PK - Placekicker",
"K/P/Slot":"PK - Placekicker",
"K/P/WR":"PK - Placekicker",
"K/PÃ¯Â¿Â½":"PK - Placekicker",
"K/QB":"PK - Placekicker",
"K/RB":"PK - Placekicker",
"K/S":"PK - Placekicker",
"K/WR":"PK - Placekicker",
"K; P":"PK - Placekicker",
"KAT":"PK - Placekicker",
"Kicker":"PK - Placekicker",
"Kicker, Punter":"PK - Placekicker",
"Kicker/Punter":"PK - Placekicker",
"KP":"PK - Placekicker",
"K-P":"PK - Placekicker",
"KR":"Ath - Athlete",
"LB":"LB - Linebacker",
"LB (C)":"LB - Linebacker",
"LB ":"LB - Linebacker",
"LB/CB":"LB - Linebacker",
"LB/DB":"LB - Linebacker",
"LB/DE":"LB - Linebacker",
"LB/DL":"LB - Linebacker",
"LB/FB":"LB - Linebacker",
"LB/HB":"LB - Linebacker",
"LB/K":"LB - Linebacker",
"LB/LS":"LB - Linebacker",
"LB/N":"LB - Linebacker",
"LB/OL":"LB - Linebacker",
"LB/P":"LB - Linebacker",
"LB/PK":"LB - Linebacker",
"LB/RB":"LB - Linebacker",
"LB/S":"LB - Linebacker",
"LB/Sn":"LB - Linebacker",
"LB/SS":"LB - Linebacker",
"LB/TE":"LB - Linebacker",
"LBÃ¯Â¿Â½":"LB - Linebacker",
"LBL":"LB - Linebacker",
"LG":"OG - Offensive Guard",
"LG/C":"OG - Offensive Guard",
"Linebacker":"LB - Linebacker",
"Linebacker/Defensive Line":"LB - Linebacker",
"Linebackers":"LB - Linebacker",
"Llinebacker":"LB - Linebacker",
"LM":"Unknown",
"Long Snapper":"LS - Long Snapper",
"Longsnapper":"LS - Long Snapper",
"Long-Snapper":"LS - Long Snapper",
"Longsnapper/Defensive Back":"LS - Long Snapper",
"LS":"LS - Long Snapper",
"LS ":"LS - Long Snapper",
"LS/C":"LS - Long Snapper",
"LS/DB":"LS - Long Snapper",
"LS/DE":"LS - Long Snapper",
"LS/DL":"LS - Long Snapper",
"LS/FB":"LS - Long Snapper",
"LS/K":"LS - Long Snapper",
"LS/LB":"LS - Long Snapper",
"LS/OL":"LS - Long Snapper",
"LS/OLB":"LS - Long Snapper",
"LS/S":"LS - Long Snapper",
"LS/TE":"LS - Long Snapper",
"LS/WR":"LS - Long Snapper",
"LSÃ¯Â¿Â½":"LS - Long Snapper",
"LT":"OT - Offensive Tackle",
"LW/RW":"Unknown",
"M":"Unknown",
"M/F":"Unknown",
"Man":"Unknown",
"MF":"Unknown",
"MG":"Unknown",
"MGR":"Unknown",
"Mgr.":"Unknown",
"MLB":"MLB - Middle Linebacker",
"MLB/DE":"MLB - Middle Linebacker",
"N":"NG - Nose Guard",
"N/A":"Unknown",
"NB":"Unknown",
"NG":"NG - Nose Guard",
"NG/T":"NG - Nose Guard",
"Nick":"DB - Defensive Back",
"Nickel":"DB - Defensive Back",
"NK":"Unknown",
"Nose Guard":"NG - Nose Guard",
"NT":"NT - Nose Tackle",
"OB":"Unknown",
"OC":"C - Center",
"OC/OG":"C - Center",
"OC/OL":"C - Center",
"Offensive Line":"OL - Offensive Lineman",
"Offensive Line/Defensive End":"OL - Offensive Lineman",
"Offensive Lineman":"OL - Offensive Lineman",
"Offensive Tackle":"OT - Offensive Tackle",
"OG":"OG - Offensive Guard",
"OG/C":"OG - Offensive Guard",
"OG/DT":"OG - Offensive Guard",
"OG/OC":"OG - Offensive Guard",
"OG/OT":"OG - Offensive Guard",
"OG/OT/DE":"OG - Offensive Guard",
"OL":"OL - Offensive Lineman",
"OL":"OL - Offensive Lineman",
"OL / LS":"OL - Offensive Lineman",
"OL / TE":"OL - Offensive Lineman",
"OL ":"OL - Offensive Lineman",
"OL, DL":"OL - Offensive Lineman",
"OL/ DL":"OL - Offensive Lineman",
"OL/16":"OL - Offensive Lineman",
"OL/C":"OL - Offensive Lineman",
"OL/DE":"OL - Offensive Lineman",
"OL/DL":"OL - Offensive Lineman",
"OL/DL ":"OL - Offensive Lineman",
"OL/DS":"OL - Offensive Lineman",
"OL/DT":"OL - Offensive Lineman",
"OL/FB":"OL - Offensive Lineman",
"OL/G":"OL - Offensive Lineman",
"OL/K":"OL - Offensive Lineman",
"OL/LB":"OL - Offensive Lineman",
"OL/LS":"OL - Offensive Lineman",
"OL/LT":"OL - Offensive Lineman",
"OL/TE":"OL - Offensive Lineman",
"OL;OG":"OL - Offensive Lineman",
"OL`":"OL - Offensive Lineman",
"OLÃ¯Â¿Â½":"OL - Offensive Lineman",
"OLB":"OLB - Outside Linebacker",
"OLB/DB":"OLB - Outside Linebacker",
"OLB/DE":"OLB - Outside Linebacker",
"OLB/FS":"OLB - Outside Linebacker",
"OLB/P":"OLB - Outside Linebacker",
"OLB/SS":"OLB - Outside Linebacker",
"OLB/WR":"OLB - Outside Linebacker",
"OLDL":"OL - Offensive Lineman",
"OS":"Unknown",
"OT":"OT - Offensive Tackle",
"OT/DL":"OT - Offensive Tackle",
"Outside Linebacker":"OLB - Outside Linebacker",
"P":"P - Punter",
"P / K":"P - Punter",
"P/CB":"P - Punter",
"P/DB":"P - Punter",
"P/H":"P - Punter",
"P/K":"P - Punter",
"P/K/LS":"P - Punter",
"P/K/WR":"P - Punter",
"P/LB":"P - Punter",
"P/OLB":"P - Punter",
"P/PK":"P - Punter",
"P/QB":"P - Punter",
"P/RB":"P - Punter",
"P/S":"P - Punter",
"P/SS":"P - Punter",
"P/TE":"P - Punter",
"P/WR":"P - Punter",
"P/WR/DB":"P - Punter",
"P;K":"P - Punter",
"PK":"PK - Placekicker",
"P-K":"PK - Placekicker",
"PK / P":"PK - Placekicker",
"PK//DL":"PK - Placekicker",
"PK/DL":"PK - Place Kicker",
"PK/K":"PK - Placekicker",
"PK/P":"PK - Placekicker",
"PK-P":"PK - Place Kicker",
"PL":"PK - Place Kicker",
"Place Kicker":"PK - Placekicker",
"Placekicker":"PK - Placekicker",
"Place-Kicker":"PK - Placekicker",
"P-QB":"P - Punter",
"Punter":"P - Punter",
"Punter/Kicker":"P - Punter",
"Punter-Tight End":"P - Punter",
"QB":"QB - Quarterback",
"QB (C)":"QB - Quarterback",
"QB / WR":"QB - Quarterback",
"QB ":"QB - Quarterback",
"QB/ATH":"QB - Quarterback",
"QB/DB":"QB - Quarterback",
"QB/DE":"QB - Quarterback",
"QB/FS":"QB - Quarterback",
"QB/H":"QB - Quarterback",
"QB/K":"QB - Quarterback",
"QB/LB":"QB - Quarterback",
"QB/LS":"QB - Quarterback",
"QB/P":"QB - Quarterback",
"QB/PK":"QB - Quarterback",
"QB/RB":"QB - Quarterback",
"QB/SB":"QB - Quarterback",
"QB/TE":"QB - Quarterback",
"QB/WR":"QB - Quarterback",
"QB/WR/DB":"QB - Quarterback",
"QB/WR/RB":"QB - Quarterback",
"QBÃ¯Â¿Â½":"QB - Quarterback",
"QB-P":"QB - Quarterback",
"Quarterback":"QB - Quarterback",
"R":"SS - Strong Safety",
"R/S":"SS - Strong Safety",
"RB":"RB - Running Back",
"RB ":"RB - Running Back",
"RB, FS, S":"RB - Running Back",
"RB/CB":"RB - Running Back",
"RB/DB":"RB - Running Back",
"RB/DB/WR":"RB - Running Back",
"RB/DE":"RB - Running Back",
"RB/FS":"RB - Running Back",
"RB/HB":"RB - Running Back",
"RB/K":"RB - Running Back",
"RB/KR":"RB - Running Back",
"RB/KR/PR":"RB - Running Back",
"RB/LB":"RB - Running Back",
"RB/LS":"RB - Running Back",
"RB/OL":"RB - Running Back",
"RB/P":"RB - Running Back",
"RB/P/KR":"RB - Running Back",
"RB/QB":"RB - Running Back",
"RB/SS":"RB - Running Back",
"RB/TE":"RB - Running Back",
"RB/WR":"RB - Running Back",
"RB/WR/P":"RB - Running Back",
"RB; WR":"RB - Running Back",
"RBÃ¯Â¿Â½":"RB - Running Back",
"RE":"DE - Defensive End",
"Redshirt":"Unknown",
"RG":"OG - Offensive Guard",
"R-Jr.":"Unknown",
"ROV":"SS - Strong Safety",
"Rover":"SS - Strong Safety",
"RT":"OT - Offensive Tackle",
"Running Back":"RB - Running Back",
"Running Back/Wide Receiver":"RB - Running Back",
"RUSH":"RB - Running Back",
"S":"S - Safety",
"S/LB":"S - Safety",
"S/LS":"S - Safety",
"S/P":"S - Safety",
"S/PR":"S - Safety",
"S/PR/LS":"S - Safety",
"S/QB":"S - Safety",
"S/RB":"S - Safety",
"S/WR":"S - Safety",
"SA":"S - Safety",
"SAF":"S - Safety",
"SAF/LS":"S - Safety",
"Safety":"S - Safety",
"SB":"RB - Running Back",
"SB/TE":"RB - Running Back",
"SB/WR/DB/KR":"RB - Running Back",
"SE":"WR - Wide Receiver",
"SF":"Unknown",
"SG":"Unknown",
"Skill":"Ath - Athlete",
"SL":"WR - Wide Receiver",
"SL/KR":"WR - Wide Receiver",
"SLB":"OLB - Outside Linebacker",
"SLOT":"WR - Wide Receiver",
"Slot Receiver":"WR - Wide Receiver",
"Slot/K/P":"WR - Wide Receiver",
"SLT":"WR - Wide Receiver",
"SN":"LS - Long Snapper",
"SP":"Ath - Athlete",
"S-P":"Ath - Athlete",
"SPEC":"Ath - Athlete",
"S-PK":"S - Safety",
"SPR":"Unknown",
"Sprints":"Unknown",
"SR":"Unknown",
"Sr.":"Unknown",
"SS":"SS - Strong Safety",
"SS/CB":"SS - Strong Safety",
"SS/LB":"SS - Strong Safety",
"ST":"LB - Linebacker",
"Stinger":"LB - Linebacker",
"Strong Safety":"SS - Strong Safety",
"STUD":"Ath - Athlete",
"S-WR":"S - Safety",
"T":"OT - Offensive Tackle",
"T/DE":"OT - Offensive Tackle",
"T/DT":"OT - Offensive Tackle",
"TB":"RB - Running Back",
"TB/DB":"RB - Running Back",
"TE":"TE - Tight End",
"TE / FB":"TE - Tight End",
"TE / P":"TE - Tight End",
"TE / WR":"TE - Tight End",
"TE ":"TE - Tight End",
"TE/DB":"TE - Tight End",
"TE/DE":"TE - Tight End",
"TE/DL":"TE - Tight End",
"TE/DS":"TE - Tight End",
"TE/DT":"TE - Tight End",
"TE/FB":"TE - Tight End",
"TE/H":"TE - Tight End",
"TE/HB":"TE - Tight End",
"TE/ILB":"TE - Tight End",
"TE/K":"TE - Tight End",
"TE/LB":"TE - Tight End",
"TE/LS":"TE - Tight End",
"TE/OG":"TE - Tight End",
"TE/OL":"TE - Tight End",
"TE/OL (79)":"TE - Tight End",
"TE/OLB":"TE - Tight End",
"TE/OT":"TE - Tight End",
"TE/P":"TE - Tight End",
"TE/QB":"TE - Tight End",
"TE/RB":"TE - Tight End",
"TE/WR":"TE - Tight End",
"TE-P":"TE - Tight End",
"TG":"Unknown",
"Tight End":"TE - Tight End",
"Tight End-J-Back":"TE - Tight End",
"UB":"RB - Running Back",
"W":"RB - Running Back",
"WB":"RB - Running Back",
"WE":"DE - Defensive End",
"Whip":"LB - Linebacker",
"Wide Receiever":"WR - Wide Receiver",
"Wide Receiver":"WR - Wide Receiver",
"Wide Receiver/Defensive Back":"WR - Wide Receiver",
"Wide Receiver/Tight End":"WR - Wide Receiver",
"Wide Reciever":"WR - Wide Receiver",
"Wing":"RB - Running Back",
"WLB":"OLB - Outside Linebacker",
"Wolf":"LB - Linebacker",
"WR":"WR - Wide Receiver",
"WR / P":"WR - Wide Receiver",
"WR ":"WR - Wide Receiver",
"WR, CB":"WR - Wide Receiver",
"Wr.":"WR - Wide Receiver",
"WR/CB":"WR - Wide Receiver",
"WR/DB":"WR - Wide Receiver",
"WR/FS":"WR - Wide Receiver",
"WR/H":"WR - Wide Receiver",
"WR/K":"WR - Wide Receiver",
"WR/K/P":"WR - Wide Receiver",
"WR/KOR":"WR - Wide Receiver",
"WR/KR":"WR - Wide Receiver",
"WR/LS":"WR - Wide Receiver",
"WR/OLB":"WR - Wide Receiver",
"WR/P":"WR - Wide Receiver",
"WR/P/K":"WR - Wide Receiver",
"WR/PK":"WR - Wide Receiver",
"WR/PR":"WR - Wide Receiver",
"WR/QB":"WR - Wide Receiver",
"WR/RB":"WR - Wide Receiver",
"WR/RB/DB":"WR - Wide Receiver",
"WR/RET":"WR - Wide Receiver",
"WR/RS":"WR - Wide Receiver",
"WR/S":"WR - Wide Receiver",
"WR/SL":"WR - Wide Receiver",
"WR/SS":"WR - Wide Receiver",
"WR/TE":"WR - Wide Receiver",
"WR\LS":"WR - Wide Receiver",
"WR\P":"WR - Wide Receiver",
"WR-DB":"WR - Wide Receiver",
"WR-QB":"WR - Wide Receiver",
"WS":"WR - Wide Receiver",
"":"Unknown",
"OLB/DL":"OLB - Outslide Linebacker",
"CB*":"CB - Cornerback",
"DB*":"DB - Defensive Back",
"DB**":"DB - Defensive Back",
"DB/ATH":"DB - Defensive Back",
"DE*":"DE - Defensive End",
"DE**":"DE - Defensive End",
"DG":"LB - Linebacker",
"DT*":"DT - Defensive Tackle",
"DT**":"DT - Defensive Tackle",
"DT/NT":"DT - Defensive Tackle",
"DT/OL**":"DT - Defensive Tackle",
"FS*":"FS - Free Safety",
"ILB/P":"MLB - Middle Linebacker",
"K,P":"PK - Place Kicker",
"K/DB/WR":"PK - Place Kicker",
"LB*":"LB - Linebacker",
"LB**":"LB - Linebacker",
"LB/DE/OL":"LB - Linebacker",
"LB/K/P":"LB - Linebacker",
"OL**":"OL - Offensive Line",
"OL/DE/TE":"OL - Offensive Line",
"OLB/LS":"OLB - Outslide Linebacker",
"RB**":"RB - Running Back",
"RB/OLB":"RB - Running Back",
"TE/PK":"TE - Tight End",
"WR**":"WR - Wide Receiver",
"HBack":"RB - Running Back",
"OLB/K":"OLB - Outslide Linebacker",
"CB/P":"CB - Cornerback",
"FB/DL":"FB - Full Back",
"RB/DL":"RB - Running Back",
"Ath":"ATH - Athlete",
"WR/LB":"WR - Wide Receiver"}


ht_Dict = {"6":"72",
"53":"63",
"54":"64",
"55":"65",
"56":"66",
"57":"67",
"58":"68",
"59":"69",
"60":"72",
"61":"73",
"62":"74",
"63":"75",
"64":"76",
"65":"77",
"66":"78",
"67":"79",
"68":"80",
"69":"81",
"510":"70",
"511":"71",
"5’10":"70",
"5’11":"71",
"5’6":"66",
"5’7":"67",
"5’8":"68",
"5’9":"69",
"5-0":"60",
"5-1":"61",
"5-10":"70",
"5-101":"70",
"5-11":"71",
"5-14":"70",
"5-171":"70",
"5-2":"62",
"5-24":"62",
"5-3":"63",
"5-4":"64",
"5-5":"65",
"5-6":"66",
"5-7":"67",
"5-7.5":"67",
"5-8":"68",
"5-8.5":"68",
"5-9":"69",
"5-9.5":"69",
"6-":"72",
"6 0 - 175 lbs.":"72",
"6 0 - 182 lbs.":"72",
"6 0 - 185 lbs.":"72",
"6 0 - 186 lbs.":"72",
"6 0 - 188 lbs.":"72",
"6 0 - 192 lbs.":"72",
"6 0 - 197 lbs.":"72",
"6 0 - 199 lbs.":"72",
"6 0 - 202 lbs.":"72",
"6 0 - 208 lbs.":"72",
"6 0 - 218 lbs.":"72",
"6 0 - 220 lbs.":"72",
"6 0 - 225 lbs.":"72",
"6 0 - 235 lbs.":"72",
"6 0 - 250 lbs.":"72",
"6 0 - 270 lbs.":"72",
"6 1 - 165 lbs.":"73",
"6 1 - 175 lbs.":"73",
"6 1 - 190 lbs.":"73",
"6 1 - 195 lbs.":"73",
"6 1 - 210 lbs.":"73",
"6 1 - 219 lbs.":"73",
"6 1 - 225 lbs.":"73",
"6 1 - 230 lbs.":"73",
"6 1 - 243 lbs.":"73",
"6 1 - 287 lbs.":"73",
"6 2 - 180 lbs.":"74",
"6 2 - 185 lbs.":"74",
"6 2 - 195 lbs.":"74",
"6 2 - 196 lbs.":"74",
"6 2 - 210 lbs.":"74",
"6 2 - 218 lbs.":"74",
"6 2 - 230 lbs.":"74",
"6 2 - 250 lbs.":"74",
"6 2 - 280 lbs.":"74",
"6 2 - 285 lbs.":"74",
"6 2 - 301 lbs.":"74",
"6 3 - 185 lbs.":"75",
"6 3 - 195 lbs.":"75",
"6 3 - 201 lbs.":"75",
"6 3 - 205 lbs.":"75",
"6 3 - 215 lbs.":"75",
"6 3 - 229 lbs.":"75",
"6 3 - 233 lbs.":"75",
"6 3 - 236 lbs.":"75",
"6 3 - 255 lbs.":"75",
"6 3 - 300 lbs.":"75",
"6 3 - 305 lbs.":"75",
"6 4 - 210 lbs.":"76",
"6 4 - 228 lbs.":"76",
"6 4 - 232 lbs.":"76",
"6 4 - 259 lbs.":"76",
"6 4 - 260 lbs.":"76",
"6 4 - 270 lbs.":"76",
"6 4 - 280 lbs.":"76",
"6 4 - 281 lbs.":"76",
"6 4 - 285 lbs.":"76",
"6 4 - 318 lbs.":"76",
"6 4 - 346 lbs.":"76",
"6 4 - 360 lbs.":"76",
"6 5 - 250 lbs.":"77",
"6 5 - 265 lbs.":"77",
"6 5 - 290 lbs.":"77",
"6 5 - 295 lbs.":"77",
"6 5 - 301 lbs.":"77",
"6 5 - 325 lbs.":"77",
"6 5 - 330 lbs.":"77",
"6 5 - 350 lbs.":"77",
"6 6 - 230 lbs.":"78",
"6 6 - 250 lbs.":"78",
"6 6 - 305 lbs.":"78",
"6 9 - 312 lbs.":"81",
"6 9 - 315 lbs.":"81",
"6*1":"73",
"6;0":"72",
"6’0":"72",
"6’1":"73",
"6’2":"74",
"6’3":"75",
"6’4":"76",
"6’5":"77",
"6’6":"78",
"6-0":"72",
"6--0":"72",
"6-1":"73",
"6-10":"82",
"6-11":"83",
"6-2":"73",
"6-225":"72",
"6-3":"75",
"6-4":"76",
"6-5":"77",
"6-6":"78",
"6-7":"79",
"6-8":"80",
"6-9":"81",
"7-0":"84",
"7-1":"85",
"4-11":"59",
"4-11":"59",
"5-1":"61",
"5/2":"62",
"5-2":"62",
"5-24":"62",
"5/3":"63",
"5/4":"64",
"5-4":"64",
"5'4":"64",
"5/5":"65",
"5'5":"65",
"5-5":"65",
"5'5":"65",
"5/6":"66",
"5-6":"66",
"5'6":"66",
"5/7":"67",
"5'7":"67",
"5-7":"67",
"5--7":"67",
"5'7":"67",
"5-7.5":"67",
"58":"68",
"58":"68",
"5/8":"68",
"5'8":"68",
"5-8":"68",
"5'8":"68",
"5-8.5":"68",
"5/9":"69",
"5'9":"69",
"5'9''":"69",
"5-9":"69",
"5'9":"69",
"5-9.5":"69",
"5-910":"69",
"5/10":"70",
"5'10":"70",
"5-10":"70",
"5'10":"70",
"5-100":"70",
"5' 11":"71",
"5/11":"71",
"5'11":"71",
"5'11''":"71",
"5-11":"71",
"5'11":"71",
"5-14":"71",
"6-":"72",
"6'0":"72",
"6'0''":"72",
"6-0":"72",
"6'0":"72",
"6*1":"73",
"6/1":"73",
"6/10":"73",
"6'1":"73",
"6-1":"73",
"6'1":"73",
"6-10":"73",
"6-11":"73",
"6-12":"73",
"6-13":"73",
"6-14":"73",
"6-15":"73",
"6-16":"73",
"6-17":"73",
"6-18":"73",
"6-19":"73",
"6/2":"74",
"6/20":"74",
"6'2":"74",
"6-2":"74",
"6'2":"74",
"6-20":"74",
"6-21":"74",
"6-22":"74",
"6-225":"74",
"6-23":"74",
"6-24":"74",
"6-25":"74",
"6/3":"75",
"6'3":"75",
"6-3":"75",
"6'3":"75",
"6-36-1":"75",
"6/4":"76",
"6'4":"76",
"6-4":"76",
"6'4":"76",
"6/5":"77",
"6'5":"77",
"6-5":"77",
"6'5":"77",
"6/6":"78",
"6'6":"78",
"6-6":"78",
"6'6":"78",
"6/7":"79",
"6-7":"79",
"6/8":"80",
"6-8":"80",
"6'8":"80",
"6-9":"81",
"6/9":"84",
"5-Jun":"77"
}

st_Dict = {" ":"unknown",
",Tx":"tx",
"AB":"international",
"ABCanada":"international",
"Abu DhabiUnited Arab Emirates":"international",
"Africa":"international",
"AK":"ak",
"AL":"al",
"AL ":"al",
"Ala":"al",
"Ala ":"al",
"Alabama":"al",
"Alaska":"ak",
"Alaska ":"ak",
"Alberta":"international",
"AlbertaCanada":"international",
"America Samoa":"unknown",
"American Samoa":"unknown",
"American Somoa":"unknown",
"AR":"ar",
"AR ":"ar",
"Ariz":"az",
"Ariz ":"az",
"Arizona":"az",
"Ark":"ar",
"Arkansas":"ar",
"AS":"international",
"Aus":"international",
"Australia":"international",
"Austria":"international",
"Austrila":"international",
"AZ":"az",
"AZ ":"az",
"Bahamas":"international",
"BC":"international",
"BCCanada":"international",
"Beach Fla":"fl",
"Belgium":"international",
"Bosnia":"international",
"Brazil":"international",
"British Colombia":"international",
"British Columbia":"international",
"BrooklynNY":"ny",
"CA":"ca",
"CA ":"ca",
"Cailf":"ca",
"Cal":"ca",
"Cali":"ca",
"Calif":"ca",
"Calif ":"ca",
"California":"ca",
"Canada":"international",
"China":"international",
"CO":"co",
"Col":"co",
"Colo":"co",
"Colo ":"co",
"Colorado":"co",
"Conn":"ct",
"Connecticut":"ct",
"CT":"ct",
"d":"unknown",
"DC":"dc",
"DE":"de",
"Del":"de",
"Delaware":"de",
"Denmark":"international",
"DenverColo":"co",
"Ecuador":"international",
"El Salvador":"international",
"England":"international",
"FC":"international",
"Fiji":"international",
"Finland":"international",
"FL":"fl",
"FL ":"fl",
"Fla":"fl",
"Fla ":"fl",
"Fla,":"fl",
"Florida":"fl",
"Forida":"fl",
"France":"international",
"France ":"international",
"Ga":"ga",
"GA ":"ga",
"Ga,":"ga",
"Gambia":"international",
"Georgia":"international",
"Ger":"international",
"Germany":"international",
"Germany ":"international",
"Ghana":"international",
"Great Britain":"international",
"GU":"gu",
"Guam":"gu",
"Haiti":"international",
"Haw":"hi",
"Hawai‘i":"hi",
"Hawaii":"hi",
"Hawai'i":"hi",
"HI":"hi",
"HillCA":"ca",
"Holland":"international",
"HS":"international",
"IA":"ia",
"ID":"id",
"Idaho":"id",
"IL":"il",
"Ill":"il",
"Ill ":"il",
"Illinois":"il",
"IN":"in",
"Ind":"in",
"Ind ":"in",
"Indiana":"in",
"Iowa":"ia",
"Ireland":"international",
"Israel":"international",
"Italy":"international",
"JacksonvilleFla":"fl",
"Jamaica":"international",
"Japan":"international",
"JctVt":"vt",
"Kan":"ks",
"Kan ":"ks",
"Kans":"ks",
"Kansas":"ks",
"Kentucky":"ky",
"Kenya":"international",
"KS":"ks",
"KS ":"ks",
"KY":"ky",
"Ky ":"ky",
"Ky,":"ky",
"La":"la",
"LA ":"la",
"lll":"il",
"Louisiana":"la",
"Louisianna":"la",
"MA":"ma",
"Maine":"ma",
"Mali Africa":"international",
"Manitoba":"international",
"ManitobaCAN":"international",
"ManitobaCanada":"international",
"Mary":"unknown",
"Maryland":"md",
"Mass":"ma",
"Mass ":"ma",
"Mass,":"ma",
"Massachusetts":"ma",
"MB":"unknown",
"Md":"md",
"ME":"me",
"Mexico":"international",
"MI":"mi",
"Mich":"mi",
"Mich ":"mi",
"Michgan":"mi",
"Michigan":"mi",
"Minas GeraisBrazil":"international",
"Minn":"mn",
"Minn ":"mn",
"Minnesota":"mn",
"Miss":"ms",
"Miss ":"ms",
"Mississippi":"ms",
"Missouri":"ms",
"MN":"mn",
"Mo":"mo",
"MO ":"mo",
"Mont":"mt",
"Montana":"mt",
"MS":"ms",
"MT":"mt",
"N J":"nj",
"NC":"nc",
"ND":"nd",
"ND,":"nd",
"NE":"ne",
"Neb":"ne",
"Neb ":"ne",
"Neb,":"ne",
"Nebraksa":"ne",
"Nebraska":"ne",
"Netherlands":"international",
"Nev":"nv",
"Nevada":"nv",
"New Jersey":"nj",
"New Mexico":"nm",
"New York":"ny",
"New Zealand":"international",
"NH":"nh",
"Nigeria":"international",
"NigeriaAfrica":"international",
"NJ":"nj",
"NJ ":"nj",
"NJ,":"nj",
"NM":"nm",
"North Carolina":"nc",
"North Dakota":"nd",
"Norway":"international",
"Nova Scotia":"international",
"NSWAustralia":"international",
"NV":"nv",
"NY":"ny",
"NY ":"ny",
"NY>":"ny",
"OH":"oh",
"Ohio":"oh",
"OK":"ok",
"OK ":"ok",
"Oka":"ok",
"Okla":"ok",
"Okla ":"ok",
"Oklahoma":"ok",
"ON":"international",
"Ont":"international",
"Ont Canada":"international",
"Ontario":"international",
"OntarioCanada":"international",
"OR":"or",
"Ore":"or",
"Ore ":"or",
"Oreg":"or",
"Oregon":"or",
"Osaka Japan":"international",
"Pa":"pa",
"Pakistan":"international",
"Panama":"international",
"ParkNJ":"nj",
"Penn":"pa",
"Pennsylvania":"pa",
"Poland":"international",
"PR":"pr",
"Puerto Rico":"pr",
"Que":"international",
"Quebec":"international",
"QuebecCanada":"international",
"QueenslandAustralia":"international",
"Rhineland-PalatinateGermany":"international",
"RI":"ri",
"Russia":"international",
"Sask":"international",
"Saskatchewan":"international",
"SaskatchewanCanada":"international",
"SC":"sc",
"Scotland":"international",
"SD":"sd",
"Senegal":"international",
"Serbia":"international",
"Sierra Leone":"international",
"SK":"international",
"South Africa":"international",
"South Australia":"international",
"South Carolina":"sc",
"South Dakota":"sd",
"South Korea":"international",
"Spain":"international",
"Sweden":"international",
"Sweden ":"international",
"Taiwan":"international",
"TampsMexico":"international",
"Tenn":"tn",
"Tenn ":"tn",
"Tennessee":"tn",
"Tesxas":"tx",
"Tex":"tx",
"Texa":"tx",
"Texas":"tx",
"Texas ":"tx",
"The Gambia":"international",
"TN":"tn",
"Trinidad and Tobago":"international",
"TV":"international",
"TwpMich":"mi",
"TX":"tx",
"TX ":"tx",
"UAE":"international",
"United Arab Emerites":"international",
"United Kingdom":"international",
"US Virgin Island":"usvi",
"US Virgin Islands":"usvi",
"USVI":"usvi",
"UT":"ut",
"Utah":"ut",
"Va":"va",
"Va,":"va",
"Vermont":"vt",
"VictoriaAustralia":"international",
"Virgin Islands":"usvi",
"Virginia":"va",
"VT":"vt",
"W Va":"wv",
"WA":"wa",
"WAfrica":"international",
"Wash":"wa",
"Wash,":"wa",
"Washington":"wa",
"Western Australia":"international",
"WI":"wi",
"Wis":"wi",
"Wis ":"wi",
"Wisc":"wi",
"Wisconsin":"wi",
"Wsh":"wa",
"WV":"wv",
"WVa":"wv",
"WY":"wy",
"Wyo":"wy",
"Wyoming":"wy",
"MD":"md",
"":"unkown"}

st_Dict = {" ":"unknown",
",Tx":"tx",
"AB":"international",
"ABCanada":"international",
"Abu DhabiUnited Arab Emirates":"international",
"Africa":"international",
"AK":"ak",
"AL":"al",
"AL ":"al",
"Ala":"al",
"Ala ":"al",
"Alabama":"al",
"Alaska":"ak",
"Alaska ":"ak",
"Alberta":"international",
"AlbertaCanada":"international",
"America Samoa":"unknown",
"American Samoa":"unknown",
"American Somoa":"unknown",
"AR":"ar",
"AR ":"ar",
"Ariz":"az",
"Ariz ":"az",
"Arizona":"az",
"Ark":"ar",
"Arkansas":"ar",
"AS":"international",
"Aus":"international",
"Australia":"international",
"Austria":"international",
"Austrila":"international",
"AZ":"az",
"AZ ":"az",
"Bahamas":"international",
"BC":"international",
"BCCanada":"international",
"Beach Fla":"fl",
"Belgium":"international",
"Bosnia":"international",
"Brazil":"international",
"British Colombia":"international",
"British Columbia":"international",
"BrooklynNY":"ny",
"CA":"ca",
"CA ":"ca",
"Cailf":"ca",
"Cal":"ca",
"Cali":"ca",
"Calif":"ca",
"Calif ":"ca",
"California":"ca",
"Canada":"international",
"China":"international",
"CO":"co",
"Col":"co",
"Colo":"co",
"Colo ":"co",
"Colorado":"co",
"Conn":"ct",
"Connecticut":"ct",
"CT":"ct",
"d":"unknown",
"DC":"dc",
"DE":"de",
"Del":"de",
"Delaware":"de",
"Denmark":"international",
"DenverColo":"co",
"Ecuador":"international",
"El Salvador":"international",
"England":"international",
"FC":"international",
"Fiji":"international",
"Finland":"international",
"FL":"fl",
"FL ":"fl",
"Fla":"fl",
"Fla ":"fl",
"Fla,":"fl",
"Florida":"fl",
"Forida":"fl",
"France":"international",
"France ":"international",
"Ga":"ga",
"GA ":"ga",
"Ga,":"ga",
"Gambia":"international",
"Georgia":"international",
"Ger":"international",
"Germany":"international",
"Germany ":"international",
"Ghana":"international",
"Great Britain":"international",
"GU":"gu",
"Guam":"gu",
"Haiti":"international",
"Haw":"hi",
"Hawai‘i":"hi",
"Hawaii":"hi",
"Hawai'i":"hi",
"HI":"hi",
"HillCA":"ca",
"Holland":"international",
"HS":"international",
"IA":"ia",
"ID":"id",
"Idaho":"id",
"IL":"il",
"Ill":"il",
"Ill ":"il",
"Illinois":"il",
"IN":"in",
"Ind":"in",
"Ind ":"in",
"Indiana":"in",
"Iowa":"ia",
"Ireland":"international",
"Israel":"international",
"Italy":"international",
"JacksonvilleFla":"fl",
"Jamaica":"international",
"Japan":"international",
"JctVt":"vt",
"Kan":"ks",
"Kan ":"ks",
"Kans":"ks",
"Kansas":"ks",
"Kentucky":"ky",
"Kenya":"international",
"KS":"ks",
"KS ":"ks",
"KY":"ky",
"Ky ":"ky",
"Ky,":"ky",
"La":"la",
"LA ":"la",
"lll":"il",
"Louisiana":"la",
"Louisianna":"la",
"MA":"me",
"Maine":"me",
"Mali Africa":"international",
"Manitoba":"international",
"ManitobaCAN":"international",
"ManitobaCanada":"international",
"Mary":"unknown",
"Maryland":"md",
"Mass":"ma",
"Mass ":"ma",
"Mass,":"ma",
"Massachusetts":"ma",
"MB":"unknown",
"Md":"md",
"ME":"me",
"Mexico":"international",
"MI":"mi",
"Mich":"mi",
"Mich ":"mi",
"Michgan":"mi",
"Michigan":"mi",
"Minas GeraisBrazil":"international",
"Minn":"mn",
"Minn ":"mn",
"Minnesota":"mn",
"Miss":"ms",
"Miss ":"ms",
"Mississippi":"ms",
"Missouri":"mo",
"MN":"mn",
"Mo":"mo",
"MO ":"mo",
"Mont":"mt",
"Montana":"mt",
"MS":"ms",
"MT":"mt",
"N J":"nj",
"NC":"nc",
"ND":"nd",
"ND,":"nd",
"NE":"ne",
"Neb":"ne",
"Neb ":"ne",
"Neb,":"ne",
"Nebraksa":"ne",
"Nebraska":"ne",
"Netherlands":"international",
"Nev":"nv",
"Nevada":"nv",
"New Jersey":"nj",
"New Mexico":"nm",
"New York":"ny",
"New Zealand":"international",
"NH":"nh",
"Nigeria":"international",
"NigeriaAfrica":"international",
"NJ":"nj",
"NJ ":"nj",
"NJ,":"nj",
"NM":"nm",
"North Carolina":"nc",
"North Dakota":"nd",
"Norway":"international",
"Nova Scotia":"international",
"NSWAustralia":"international",
"NV":"nv",
"NY":"ny",
"NY ":"ny",
"NY>":"ny",
"OH":"oh",
"Ohio":"oh",
"OK":"ok",
"OK ":"ok",
"Oka":"ok",
"Okla":"ok",
"Okla ":"ok",
"Oklahoma":"ok",
"ON":"international",
"Ont":"international",
"Ont Canada":"international",
"Ontario":"international",
"OntarioCanada":"international",
"OR":"or",
"Ore":"or",
"Ore ":"or",
"Oreg":"or",
"Oregon":"or",
"Osaka Japan":"international",
"Pa":"pa",
"Pakistan":"international",
"Panama":"international",
"ParkNJ":"nj",
"Penn":"pa",
"Pennsylvania":"pa",
"Poland":"international",
"PR":"pr",
"Puerto Rico":"pr",
"Que":"international",
"Quebec":"international",
"QuebecCanada":"international",
"QueenslandAustralia":"international",
"Rhineland-PalatinateGermany":"international",
"RI":"ri",
"Russia":"international",
"Sask":"international",
"Saskatchewan":"international",
"SaskatchewanCanada":"international",
"SC":"sc",
"Scotland":"international",
"SD":"sd",
"Senegal":"international",
"Serbia":"international",
"Sierra Leone":"international",
"SK":"international",
"South Africa":"international",
"South Australia":"international",
"South Carolina":"sc",
"South Dakota":"sd",
"South Korea":"international",
"Spain":"international",
"Sweden":"international",
"Sweden ":"international",
"Taiwan":"international",
"TampsMexico":"international",
"Tenn":"tn",
"Tenn ":"tn",
"Tennessee":"tn",
"Tesxas":"tx",
"Tex":"tx",
"Texa":"tx",
"Texas":"tx",
"Texas ":"tx",
"The Gambia":"international",
"TN":"tn",
"Trinidad and Tobago":"international",
"TV":"international",
"TwpMich":"mi",
"TX":"tx",
"TX ":"tx",
"UAE":"international",
"United Arab Emerites":"international",
"United Kingdom":"international",
"US Virgin Island":"usvi",
"US Virgin Islands":"usvi",
"USVI":"usvi",
"UT":"ut",
"Utah":"ut",
"Va":"va",
"Va,":"va",
"Vermont":"vt",
"VictoriaAustralia":"international",
"Virgin Islands":"usvi",
"Virginia":"va",
"VT":"vt",
"W Va":"wv",
"WA":"wa",
"WAfrica":"international",
"Wash":"wa",
"Wash,":"wa",
"Washington":"wa",
"Western Australia":"international",
"WI":"wi",
"Wis":"wi",
"Wis ":"wi",
"Wisc":"wi",
"Wisconsin":"wi",
"Wsh":"wa",
"WV":"wv",
"WVa":"wv",
"WY":"wy",
"Wyo":"wy",
"Wyoming":"wy",
"MD":"md",
"":"unkown",
"Ak":"ak",
"Al":"al",
"Ar":"ar",
"AUS":"international",
"Az":"az",
"Ca":"ca",
"CAl":"ca",
"De":"de",
"Fl":"fl",
"GA":"ga",
"HawaiÂ‘i":"hi",
"HawaiI":"hi",
"Ia":"la",
"Id":"id",
"Il":"il",
"ill":"il",
"In":"in",
"iowa":"ia",
"Ky":"ky",
"LA":"la",
"LaÂ ":"la",
"Ma":"ma",
"Mi":"mi",
"MIch":"mi",
"Mn":"mn",
"MO":"mo",
"MoÂ ":"mo",
"Ms":"ms",
"Mt":"mt",
"Nc":"nc",
"Nd":"nd",
"Ny":"ny",
"Oh":"oh",
"OhIo":"oh",
"Ok":"ok",
"OKla":"ok",
"ONT":"international",
"Or":"or",
"PA":"pa",
"QUE":"international",
"Sc":"sc",
"texas":"tx",
"Tn":"tn",
"Tx":"tx",
"TxÂ ":"tx",
"VA":"va",
"Vt":"vt",
"Wa":"wa",
"Wi":"wi",
"Wy":"wy",
"":"unknown",
"A.S.":"international",
"AB":"international",
"AB, Canada":"international",
"Africa":"international",
"AK":"ak",
"Ak.":"ak",
"AL":"al",
"AL ":"al",
"Ala":"al",
"Ala ":"al",
"Ala.":"al",
"Ala. ":"al",
"Alabama":"al",
"Alaska":"ak",
"Alaska ":"ak",
"Alberta":"international",
"Alberta ":"international",
"Alberta, Canada":"international",
"American Samoa":"international",
"American Samoa ":"international",
"American Somoa":"international",
"AR":"ar",
"AR ":"ar",
"Ariz":"az",
"Ariz.":"az",
"Ariz. ":"az",
"Ariz. /":"az",
"Arizona":"az",
"Ark":"ar",
"Ark ":"ar",
"Ark.":"ar",
"Ark. ":"ar",
"Arkansas":"ar",
"AS":"international",
"Aus.":"international",
"Australia":"international",
"Austria":"international",
"AZ":"az",
"B.C.":"international",
"B.C., Canada":"international",
"Bahamas":"international",
"Beach Fla.":"fl",
"Belgium":"international",
"Bolivia":"international",
"Bosnia":"international",
"Brazil":"international",
"British Colombia":"international",
"British Columbia":"international",
"C.A.":"ca",
"CA":"ca",
"CA ":"ca",
"CA /":"ca",
"Ca.":"ca",
"Cailf.":"ca",
"Cailf. ":"ca",
"Cal.":"ca",
"Cali.":"ca",
"Calif":"ca",
"Calif,":"ca",
"Calif.":"ca",
"Calif. ":"ca",
"Calif. /":"ca",
"Calif. ":"ca",
"Calif..":"ca",
"California":"ca",
"California ":"ca",
"Canada":"international",
"Chile":"international",
"China":"international",
"CO":"co",
"Co.":"co",
"Col.":"co",
"Colo":"co",
"Colo.":"co",
"Colo. ":"co",
"Colo..":"co",
"Colombia":"international",
"Colorado":"co",
"Congo.":"international",
"Conn":"ct",
"Conn.":"ct",
"Conn..":"ct",
"Connecticut":"ct",
"CT":"ct",
"Czech":"international",
"D.C.":"dc",
"DC":"dc",
"DE":"de",
"Del.":"de",
"Del. ":"de",
"Delaware":"de",
"Denmark":"international",
"Denver, Colo.":"co",
"El Salvador":"international",
"England":"international",
"Finland":"international",
"FL":"fl",
"FL ":"fl",
"FL.":"fl",
"Fla":"fl",
"Fla ":"fl",
"Fla,":"fl",
"Fla.":"fl",
"Fla. ":"fl",
"Fla. ":"fl",
"Fla./":"fl",
"Florida":"fl",
"FR":"international",
"France":"international",
"GA":"ga",
"Ga ":"ga",
"Ga,":"ga",
"Ga.":"ga",
"Ga. ":"ga",
"Gambia":"international",
"Georgia":"ga",
"Ger.":"international",
"Germany":"international",
"Germany ":"international",
"Ghana":"international",
"Great Britain":"international",
"Guam":"international",
"Hawai‘i":"hi",
"Hawaii":"hi",
"Hawai'i":"hi",
"Hawaii ":"hi",
"HI":"hi",
"Hi.":"hi",
"Hi. ":"hi",
"Honduras":"international",
"Hungary":"international",
"IA":"ia",
"IA.":"ia",
"ID":"id",
"Id.":"id",
"Idaho":"id",
"Idaho ":"id",
"IL":"il",
"IL -":"il",
"IL.":"il",
"Ill":"il",
"Ill.":"il",
"Ill. ":"il",
"Ill. ":"il",
"Ill..":"il",
"Illinois":"il",
"IN":"in",
"Ind":"in",
"Ind.":"in",
"Ind. ":"in",
"Indiana":"in",
"Iowa":"ia",
"Iowa ":"ia",
"Iowa ":"ia",
"Iowa.":"ia",
"Ireland":"international",
"Israel":"international",
"Italy":"international",
"Jamaica":"international",
"Japan":"international",
"Japan ":"international",
"Jct., Vt.":"vt",
"Kan ":"ks",
"Kan.":"ks",
"Kan. ":"ks",
"Kan. /":"ks",
"Kans.":"ks",
"Kansas":"ks",
"Kas.":"ks",
"Kent.":"ky",
"Kentucky":"ky",
"KS":"ks",
"KY":"ky",
"Ky.":"ky",
"Ky..":"ky",
"LA":"la",
"La ":"la",
"La.":"la",
"La. ":"la",
"La. ":"la",
"Latvia":"international",
"lll.":"il",
"Louisiana":"la",
"Louisiana ":"la",
"M.D.":"md",
"M.T.":"mt",
"MA":"ma",
"Ma.":"ma",
"Maine":"me",
"Manitoba":"international",
"Manitoba ":"international",
"Manitoba, CAN":"international",
"Manitoba, Canada":"international",
"Maryland":"md",
"Mass":"ma",
"Mass,":"ma",
"Mass.":"ma",
"Massachusetts":"ma",
"Maui, Hawaii":"hi",
"MB":"international",
"MD":"md",
"Md.":"md",
"Md. ":"md",
"ME":"me",
"Mexico":"international",
"MI":"mi",
"Mich":"mi",
"Mich.":"mi",
"Mich. ":"mi",
"Mich..":"mi",
"Michgan":"mi",
"Michigan":"mi",
"Minn":"mn",
"Minn.":"mn",
"Minn. ":"mn",
"Minn. ":"mn",
"Minnesota":"mn",
"Minnn.":"mn",
"Mis.":"ms",
"Miss":"ms",
"Miss ":"ms",
"Miss.":"ms",
"Miss. ":"ms",
"Mississippi":"ms",
"Missouri":"mo",
"MN":"mn",
"MN -":"mn",
"MO":"mo",
"Mo ":"mo",
"Mo.":"mo",
"Mo. ":"mo",
"Mo.,":"mo",
"Mont":"mt",
"Mont.":"mt",
"Mont. ":"mt",
"Montana":"mt",
"MS":"ms",
"MS ":"ms",
"MS.":"ms",
"Ms. ":"ms",
"MT":"mt",
"N..Y.":"ny",
"N.C":"nc",
"N.C.":"nc",
"N.C. ":"nc",
"N.D,":"nd",
"N.D.":"nd",
"N.D. ":"nd",
"N.H.":"nh",
"N.H. ":"nh",
"N.J":"nj",
"N.J,":"nj",
"N.J.":"nj",
"N.J. ":"nj",
"N.M.":"nm",
"N.M. ":"nm",
"N.V.":"nv",
"N.Y":"ny",
"N.Y.":"ny",
"N.Y. ":"ny",
"NC":"nc",
"Nc.":"nc",
"ND":"nd",
"ND -":"nd",
"NE":"ne",
"Neb.":"ne",
"Neb. ":"ne",
"Nebraksa":"ne",
"Nebraska":"ne",
"Netherlands":"international",
"Nev":"nv",
"Nev.":"nv",
"Nev. ":"nv",
"Nev. /":"nv",
"Nevada":"nv",
"New Mexico":"nm",
"New South Wales, Australia":"international",
"New York":"ny",
"New Zealand":"international",
"NH":"nh",
"Nicaragua":"international",
"Nigeria":"international",
"Nigeria ":"international",
"NJ":"nj",
"NJ.":"nj",
"NJ. ":"nj",
"NM":"nm",
"North Carolina":"nc",
"North Dakota":"nd",
"Norway":"international",
"Nova Scotia":"international",
"NSW, Australia":"international",
"NV":"nv",
"NY":"ny",
"NY ":"ny",
"NY.":"ny",
"OH":"oh",
"OH ":"oh",
"OH.":"oh",
"Ohio":"oh",
"Ohio ":"oh",
"Oho":"oh",
"OK":"ok",
"OK ":"ok",
"OK.":"ok",
"Okla":"ok",
"Okla ":"ok",
"Okla.":"ok",
"Okla. ":"ok",
"Okla. /":"ok",
"Oklahoma":"ok",
"ON":"international",
"ONT ":"international",
"Ont.":"international",
"Ont. Canada":"international",
"Ontario":"international",
"Ontario, Canada":"international",
"OR":"or",
"Or.":"or",
"Ore.":"or",
"Oreg.":"or",
"Oregon":"or",
"P.R.":"pr",
"PA":"pa",
"Pa.":"pa",
"Pa. ":"pa",
"Pakistan":"international",
"Panama":"international",
"Paraguay":"international",
"Park, N.J.":"nj",
"Penn.":"pa",
"Poland":"international",
"PR":"pr",
"Puerto Rico":"pr",
"QUE":"international",
"Que.":"international",
"Quebec":"international",
"Quebec ":"international",
"Quebec, Canada":"international",
"Queensland, Australia":"international",
"R.I":"ri",
"R.I.":"ri",
"Rhineland-Palatinate, Germany":"international",
"RI":"ri",
"Russia":"international",
"S.C":"sc",
"S.C.":"sc",
"S.C. ":"sc",
"S.D.":"sd",
"Saifawa":"international",
"Sao Paulo":"international",
"Sask.":"international",
"Saskatchewan":"international",
"Saskatchewan ":"international",
"Saskatchewan, Canada":"international",
"SC":"sc",
"Sc.":"sc",
"Scotland":"international",
"SD":"sd",
"Serbia":"international",
"Sierra Leone":"international",
"SK":"international",
"South Africa":"international",
"South Australia":"international",
"South Dakota":"sd",
"South Korea":"international",
"Spain":"international",
"Sweden":"international",
"Switzerland":"international",
"T.X.":"tx",
"Taiwan":"international",
"Tamps., Mexico":"international",
"Tenn":"tn",
"Tenn ":"tn",
"Tenn.":"tn",
"Tenn. ":"tn",
"Tennessee":"tn",
"Tesxas":"tx",
"Tex.":"tx",
"Texa":"tx",
"Texas":"tx",
"Texas ":"tx",
"Texas /":"tx",
"Texas.":"tx",
"The Gambia":"international",
"TN":"tn",
"TN ":"tn",
"Tn.":"tn",
"Trinidad & Tobago":"international",
"TV":"international",
"Twp., Mich.":"mi",
"TX":"tx",
"TX ":"tx",
"TX /":"tx",
"Tx.":"tx",
"U.K.":"international",
"UAE":"international",
"UK":"international",
"United Kingdom":"international",
"USVI":"international",
"UT":"ut",
"Utah":"ut",
"Utah ":"ut",
"V.T.":"vt",
"VA":"va",
"Va.":"va",
"Va. ":"va",
"Varese, Italy":"international",
"Ve":"international",
"Venezuela":"international",
"Vermont":"vt",
"Victoria, Australia":"international",
"Virgin Islands":"international",
"Virginia":"va",
"VT":"vt",
"Vt.":"vt",
"W.V.":"wv",
"W.Va.":"wv",
"WA":"wa",
"Wa.":"wa",
"Wa. ":"wa",
"Wales":"international",
"Wash":"wa",
"Wash.":"wa",
"Wash. ":"wa",
"Washington":"wa",
"Western Australia ":"international",
"Western Australia, Aust":"international",
"WI":"wi",
"WI -":"wi",
"Wi.":"wi",
"Wis":"wi",
"Wis,":"wi",
"Wis.":"wi",
"Wis. ":"wi",
"Wis. ":"wi",
"Wisc.":"wi",
"Wisconsin":"wi",
"Wy":"wy",
"Wyo.":"wy",
"Wyo. ":"wy",
"Wyoming":"wy"}

class_Dict = {"FR":"Fr",
"FR*":"Fr",
"Fr,":"Fr",
"Fr,.":"Fr",
"Fr.":"Fr",
"Fr. ":"Fr",
"Fr..":"Fr",
"Fr./Fr.":"Fr",
"Fr.-HS":"Fr",
"Fr.-RS":"Fr",
"Fr.-TR":"Fr",
"Fr.-Tr.":"Fr",
"FR/HS":"Fr",
"FR/SO":"Fr",
"Freshamn":"Fr",
"Freshman":"Fr",
"Freshman.":"Fr",
"Freshmen":"Fr",
"Fr-HS":"Fr",
"Fr-RS":"Fr",
"Fr-TR":"Fr",
"FY":"Fr",
"FY ":"Fr",
"Fy.":"Fr",
"Fy. ":"Fr",
"JR":"Jr",
"JR ":"Jr",
"JR*":"Jr",
"Jr,":"Jr",
"Jr.":"Jr",
"Jr. (RS)":"Jr",
"Jr. ":"Jr",
"Jr.*":"Jr",
"Jr..":"Jr",
"Jr./ Tr.":"Jr",
"Jr./Fr.":"Jr",
"Jr./Jr.":"Jr",
"Jr./So.":"Jr",
"Jr./So..":"Jr",
"Jr.-1L":"Jr",
"Jr.-2L":"Jr",
"Jr.-DS":"Jr",
"Jr.-RS":"Jr",
"Jr.-TR":"Jr",
"Jr.-Tr.":"Jr",
"JR/2L":"Jr",
"JR/3L":"Jr",
"JR/SR":"Jr",
"Jr-1L":"Jr",
"Jr-2L":"Jr",
"jr-RS":"Jr",
"Jr-SQ":"Jr",
"Jr-TR":"Jr",
"Junior":"Jr",
"R.Fr.":"Fr",
"R.Jr.":"Jr",
"Redshirt":"Fr",
"Redshirt Freshman":"Fr",
"Redshirt Junior":"Jr",
"Redshirt Senior":"Sr",
"Redshirt Soph":"So",
"Redshirt Sophomore":"So",
"Rf.":"Fr",
"Rf. ":"Fr",
"RFr":"Fr",
"r-FR":"Fr",
"RFr.":"Fr",
"R-Fr.":"Fr",
"R-Fr. ":"Fr",
"r-JR":"Jr",
"RJr.":"Jr",
"R-Jr.":"Jr",
"R-Jr.  ":"Jr",
"R-Jr. ":"Jr",
"R-Jr..":"Jr",
"RS":"Fr",
"RS FR":"Fr",
"RS Freshman":"Fr",
"RS JR":"Jr",
"RS Junior":"Jr",
"RS Senior":"Sr",
"RS SO":"So",
"RS Sophomore":"So",
"RS SR":"Sr",
"Rs.":"Fr",
"RS-Fr.":"Fr",
"RS-Fr. ":"Fr",
"RS-Fr..":"Fr",
"RS-Jr.":"Jr",
"RSo":"So",
"r-SO":"So",
"RSo.":"So",
"R-So.":"So",
"R-So. ":"So",
"R-SR":"Sr",
"RSr.":"Sr",
"R-Sr.":"Sr",
"R-Sr. ":"Sr",
"RS-So.":"So",
"RS-So. ":"So",
"RS-Sr.":"Sr",
"Seniior":"Sr",
"Senior":"Sr",
"SO":"So",
"SO ":"So",
"SO*":"So",
"So.":"So",
"So. ":"So",
"So.*":"So",
"So./Fr.":"So",
"So./Fr..":"So",
"So./So.":"So",
"So./So..":"So",
"So.-1L":"So",
"So.-DS":"So",
"So.-HS":"So",
"So.-RS":"So",
"So.-SQ":"So",
"So.-TR":"So",
"So.-Tr.":"So",
"SO/1L":"So",
"SO/HS":"So",
"SO/JR":"So",
"So-1L":"So",
"So-DS":"So",
"soph":"So",
"Sophomore":"So",
"soph-RS":"So",
"So-RS":"So",
"So-SQ":"So",
"So-TR":"So",
"Sr":"Sr",
"SR ":"Sr",
"SR*":"Sr",
"Sr.":"Sr",
"Jr":"Jr",
"jr":"Jr",
"fr":"Fr",
"so":"So",
"sr":"Sr",
"Fr":"Fr",
"Sr. ":"Sr",
"fr-RS":"Fr",
"fr-Tr":"Fr",
"fr.":"Fr",
"Jr-RS":"Jr",
"jr.":"Jr",
"Jr":"Jr",
"R-FR":"Fr",
"r-Fr.":"Fr",
"R-JR":"Jr",
"R-SO":"So",
"r-So.":"So",
"r-SR":"Sr",
"r-Sr.":"Sr",
"Redshirt freshman":"Fr",
"So":"So",
"SO.":"So",
"So":"So",
"SR":"Sr",
"FR":"Fr",
"5Sr.":"Sr",
"5th":"Sr",
"Fr,":"Fr",
"Fr.":"Fr",
"Fr. ":"Fr",
"Fr..":"Fr",
"Fr.-HS":"Fr",
"Fr.-RS":"Fr",
"Fr.-TR":"Fr",
"Fr.-Tr.":"Fr",
"FR/HS":"Fr",
"FR/SO":"Fr",
"Freshman":"Fr",
"Freshmen":"Fr",
"Fr-HS":"Fr",
"Fr-RS":"Fr",
"fr-Tr":"Fr",
"FY":"Fr",
"Fy.":"Fr",
"GR":"Sr",
"Gr.":"Sr",
"Gr. ":"Sr",
"GS":"Sr",
"JR":"Jr",
"Jr,":"Jr",
"Jr.":"Jr",
"Jr. (RS)":"Jr",
"Jr. ":"Jr",
"Jr.*":"Jr",
"Jr./So.":"Jr",
"Jr.-1L":"Jr",
"Jr.-2L":"Jr",
"Jr.-DS":"Jr",
"Jr.-RS":"Jr",
"Jr.-TR":"Jr",
"Jr.-Tr.":"Jr",
"JR/2L":"Jr",
"JR/3L":"Jr",
"JR/SR":"Jr",
"Jr-1L":"Jr",
"Jr-2L":"Jr",
"jr-RS":"Jr",
"Jr-TR":"Jr",
"Junior":"Jr",
"R.Fr.":"Jr",
"Redshirt":"Fr",
"Redshirt Freshman":"Fr",
"Redshirt Junior":"Jr",
"Redshirt Sophomore":"So",
"Rf.":"Fr",
"RFr":"Fr",
"R-FR":"Fr",
"RFr.":"Fr",
"R-Fr.":"Fr",
"R-Fr. ":"Fr",
"RGr.":"Sr",
"R-JR":"Jr",
"RJr.":"Jr",
"R-Jr.":"Jr",
"R-Jr..":"Jr",
"RS":"Fr",
"RS FR":"Fr",
"RS JR":"Jr",
"RS SO":"So",
"RS SR":"Sr",
"Rs.":"Fr",
"RS-Fr":"Fr",
"RS-Fr.":"Fr",
"RS-Fr..":"Fr",
"RS-Jr.":"Jr",
"RSo":"So",
"R-SO":"So",
"RSo.":"So",
"R-So.":"So",
"R-So. ":"So",
"R-SR":"Sr",
"RSr.":"Sr",
"R-Sr.":"Sr",
"R-Sr. ":"Sr",
"RS-So":"So",
"RS-So.":"So",
"SA":"Sr",
"Seniior":"Sr",
"Senior":"Sr",
"SL":"So",
"SO":"So",
"So.":"So",
"So. ":"So",
"So.*":"So",
"So..":"So",
"So.-1L":"So",
"So.-DS":"So",
"So.-HS":"So",
"So.-RS":"So",
"So.-SQ":"So",
"So.-TR":"So",
"So.-Tr.":"So",
"SO/1L":"So",
"SO/HS":"So",
"SO/JR":"So",
"So-1L":"So",
"So-DS":"So",
"soph":"So",
"Sophomore":"So",
"soph-RS":"So",
"So-RS":"So",
"So-TR":"So",
"SR":"Sr",
"Sr.":"Sr",
"Sr. ":"Sr",
"Sr.-1L":"Sr",
"Sr.-2L":"Sr",
"Sr.-3L":"Sr",
"Sr.-DS":"Sr",
"Sr.-RS":"Sr",
"Sr.-SQ":"Sr",
"Sr.-TR":"Sr",
"Sr.-Tr.":"Sr",
"SR/2L":"Sr",
"SR/3L":"Sr",
"SR/GR":"Sr",
"SR/TR":"Sr",
"Sr-1L":"Sr",
"Sr-2L":"Sr",
"Sr-3L":"Sr",
"sr-RS":"Sr",
"Sr-TR":"Sr",
"Tr.":"Fr",
"Unk":"Fr",
"Gr":"Sr",
"R-Fr":"Fr",
"RF.":"Fr",
"Sr./Sr.":"Sr",
"Sr./Jr.":"Sr",
"R-So":"So",
"R-Sr":"So",
"Fr/Fr":"Fr",
"RSJr":"Jr",
"RSFr":"Fr",
"So/So":"So",
"RSSo":"So",
"Jr/Jr":"Jr",
"So,So":"So",
"Sr/Sr":"Sr",
"Sr/Jr":"Sr",
"RSSr.":"Sr",
"Graduate":"Sr",
"Fy":"Fr",
"RSFr.":"Fr",
"FY/SO":"Fr",
"SO/SR":"So",
"G-Sr.":"Sr",
"Sr.(RS)":"Sr",
"Jr./Jr,":"Jr",
"Sr./So.":"Sr",
"Gr./Sr.":"Sr"}

subpoc_to_pos_Dict = {"PK - Placekicker":"PK - Placekicker",
"DE - Defensive End":"DL - Defensive Lineman",
"LS - Long Snapper":"LS - Long Snapper",
"CB - Cornerback":"DB - Defensive Back",
"S - Safety":"DB - Defensive Back",
"FB - Fullback":"RB - Running Back",
"DT - Defensive Tackle":"DL - Defensive Lineman",
"FS - Free Safety":"DB - Defensive Back",
"C - Center":"OL - Offensive Lineman",
"SS - Strong Safety":"DB - Defensive Back",
"OLB - Outside Linebacker":"LB - Linebacker",
"ILB - Inside Linebacker":"LB - Linebacker",
"OG - Offensive Guard":"OL - Offensive Lineman",
"OT - Offensive Tackle":"OL - Offensive Lineman",
"MLB - Middle Linebacker":"LB - Linebacker",
"HB - Halfback":"RB - Running Back",
"NT - Nose Tackle":"DL - Defensive Lineman",
"SN - Snapper":"LS - Long Snapper",
"LS - Long Snapper":"LS - Long Snapper",
"TB - Tailback":"RB - Running Back",
"NG - Nose Guard":"DL - Defensive Lineman",
"SB - Slotback":"RB - Running Back"}

# roster_comb['position'] = roster_comb['Pos.'].map(pos_Dict)
# roster_comb['height'] = roster_comb['Ht'].map(ht_Dict)
# #roster_comb['state'] = roster_comb['State'].map(st_Dict)
# roster_comb['Class'] = roster_comb['Yr'].map(class_Dict)
# roster_comb['Univ'] = roster_comb['University'].map(univ_Dict)
# roster_comb['full_pos'] = roster_comb['position'].map(subpoc_to_pos_Dict)


#roster_comb['school'] = [x.strip() for x in roster_comb['school']]
#roster_comb['school'] = [x.encode('ascii',errors='ignore') for x in roster_comb['school']]
#roster_comb['school'] = roster_comb['school'].apply(str)
#roster_comb['school']  = roster_comb['school'] .map(lambda x: x.replace("b'", ""))
#roster_comb['school']  = roster_comb['school'] .map(lambda x: x.replace("'", ""))


#sch_Dict = {"Alabama A & M University":"Alabama A&M University",
#"Bethel College-North Newton":"Bethel College North Newton",
#"Cal Poly San Luis Obispo":"California Polytechnic State University",
#"Cincinnati Christian University":"",
#"Claremont Mudd Scripps":"Claremont-Mudd-Scripps",
#"Concordia University-Chicago":"Concordia University Chicago",
#"Concordia Unviversity Ann Arbor":"Concordia University Ann Arbor",
#"Eastern Central University":"East Central University",
#"Finchburg State University":"Fitchburg State University",
#"Florida A & M University":"Florida A&M University",
#"Hardin Simmons University":"Hardin-Simmons University",
#"Ithica College":"Ithaca College",
#"Lindenwood University - Belleville":"Lindenwood University Belleville",
#"Lousiana Tech University":"Louisiana Tech University",
#"Massachusetts Maritim Academy":"Massachusetts Maritime Academy",
#"Montana Tech":"Montana Tech of the University of Montan",
#"Mount Saint Joseph University":"Mount St. Joseph University",
#"Northwood Univeristy Michigan":"Northwood University Michigan",
#"Pace University":"Pace University New York",
#"Prairie View A & M University":"Prairie View A&M University",
#"Randolph Macon College":"Randolph-Macon College",
#"Rose Hulman Institute of Technology":"Rose-Hulman Institute of Technology",
#"Sacramento State University":"California State University Sacramento",
#"Saint Anselm College":"St. Anselm College",
#"Saint John Fisher College":"St. John Fisher College",
#"Saint Lawrence University":"St. Lawrence University",
#"Saint Xavier University":"St. Xavier University",
#"Sewanee-The University of the South":"Sewanee: The University of the South",
#"South Dakota School of Mines & Tech":"South Dakota School of Mines and Technol",
#"Southwestern Assemblies of God University":"Southwestern Assemblies of God Universit",
#"Soutwestern University":"Southwestern University",
#"St Lawrence University":"St. Lawrence University",
#"SUNY at Albany":"SUNY Albany",
#"SUNY College at Brockport":"SUNY College Brockport",
#"SUNY College at Cortland":"SUNY Cortland",
#"SUNY College of Technology at Alfred":"SUNY College of Technology Alfred",
#"Tennessee Tech University":"Tennessee Technological University",
#"Texas A & M University Commerce":"Texas A&M University Commerce",
#"Texas A & M University Kingsville":"Texas A&M University Kingsville",
#"Texas Luteran University":"Texas Lutheran University",
#"University of Alabama at Birmingham":"University of Alabama Birmingham",
#"University of Massachusett at Dartmouth":"University of Massachusetts Dartmouth",
#"University of Saint Francis":"University of St. Francis",
#"University of Saint Mary":"University of St. Mary",
#"University of St Francis":"University of St. Francis",
#"University of Tennessee-Chattanooga":"University of Tennessee Chattanooga",
#"University of Tennessee-Martin":"University of Tennessee Martin",
#"University of Virginia - Wise":"University of Virginia Wise",
#"US Merchant Marine Academy":"U.S. Merchant Marine Academy",
#"Virginia Stat University":"Virginia State University",
#"Washington & Lee":"Washington & Lee University",
#"West Texas A & M University":"West Texas A&M University",
#"West Virginia Wesleyan":"West Virginia Wesleyan College",
#"Williamette University":"Willamette University"}
#
#posabb_Dict = {"Athlete":"ATH",
#"Defensive Back":"DB",
#"Defensive Line":"DL",
#"Linebacker":"LB",
#"Long Snapper":"LS",
#"Offensive Line":"OL",
#"Placekicker":"PK",
#"Punter":"P",
#"Quarterback":"QB",
#"Running Back":"RB",
#"Tight End":"TE",
#"Unknown":"Unknown",
#"Wide Reciever":"WR",
#"":"Unknown"}
#
#roster_comb['position_pull'] = roster_comb['Pos.'].map(pos_Dict)
#roster_comb['height'] = roster_comb['Ht.'].map(ht_Dict)
#roster_comb['state'] = roster_comb['St.'].map(st_Dict)
#roster_comb['class'] = roster_comb['Yr.'].map(class_Dict)
##roster_comb['school'] = roster_comb['school'].map(sch_Dict)
#roster_comb['position'] = roster_comb['position_pull'].map(posabb_Dict)
#
#
#roster_comb['school'] = roster_comb['school'].replace(sch_Dict, regex=True)
#
#
#Univ = pd.read_csv("C:/Route/Rr/Modeling/Model_Univs/New folder/univsv2.csv", encoding='ISO-8859-1')
#Univ = Univ[['id','university','proper_name','division_id']]
#data = pd.merge(roster_comb, Univ, left_on='school', right_on='university', how='left')
#
#data.to_csv("C:/Route/Rr/Data/Data_Sources/Rosters/Interns/Copyros_cleanv3.csv")